name: php
on:
  push:
    branches:
    - master
    paths:
    - 'Dockerfile'
    - '.github/workflows/build_and_push.yaml'
jobs:
  build_and_push:
    name: Build and Push Image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Image
      env:
        IMAGE_TAG: v0.1.0
      run: |-
        CMD="docker run \
          -v `pwd`:/workspace \
          -v ${DOCKER_CONFIG}/config.json:/kaniko/.docker/config.json:ro \
          gcr.io/kaniko-project/executor:latest \
          --dockerfile Dockerfile \
          --context dir:///workspace/ \
          --destination roxxinc/docker-alpine-php-fpm:latest \
          --destination roxxinc/docker-alpine-php-fpm:${IMAGE_TAG} \
          --cache=true \
          --cache-repo roxxinc/docker-alpine-php-fpm-cache"

